[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "selective_attention"
version = "0.1.0"
description = "Selective attention library"
requires-python = ">=3.9"

dependencies = [
    "torch",
    "packaging"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]